version: "3.0"

services:
  onepixel:
    container_name: onepixel
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onepixel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
    expose:
      - "5432"
    ports:
      - "5432:5432"
